In [1]:
a = ['red','red','red','blue','green','green','blue']
p = {c:i for i,c in enumerate(set(a))}
for i in enumerate(set(a)):
    print(i)

(0, 'red')
(1, 'blue')
(2, 'green')


In [2]:
import numpy as np

In [3]:
ohe = np.zeros((len(a),len(p)),dtype='int')
ohe

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
for i,c in enumerate(a):
    ohe[i][p[c]] = 1
ohe

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0]])

In [14]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# List of categorical values
categories = ["Red", "Green", "Blue", "Green", "Red"]

# Create an instance of the OneHotEncoder
encoder = OneHotEncoder()

# Reshape the data to a 2D array (necessary for the encoder)
categories_2d = np.array(categories).reshape(-1,1)

# Fit and transform the data using the encoder
one_hot_encoded = encoder.fit_transform(categories_2d)

# Convert the sparse matrix to a dense array
one_hot_encoded_array = one_hot_encoded.toarray()

print("Original Categories:", categories)
print("One-Hot Encoded Array:\n", one_hot_encoded_array)

Original Categories: ['Red', 'Green', 'Blue', 'Green', 'Red']
One-Hot Encoded Array:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
import pandas as pd

# Create a DataFrame with a categorical column
data = {'Color': ['Red', 'Green', 'Blue', 'Green', 'Red']}
df = pd.DataFrame(data)
# Apply one-hot encoding to the 'Color' column
one_hot_encoded = pd.get_dummies(df['Color'])

# Concatenate the one-hot encoded columns with the original DataFrame
df_encoded = pd.concat([df, one_hot_encoded], axis=1)
df_encoded
print("Original DataFrame:")
print(df)

print("\nDataFrame with One-Hot Encoded Columns:")
print(df_encoded)

Original DataFrame:
   Color
0    Red
1  Green
2   Blue
3  Green
4    Red

DataFrame with One-Hot Encoded Columns:
   Color  Blue  Green  Red
0    Red     0      0    1
1  Green     0      1    0
2   Blue     1      0    0
3  Green     0      1    0
4    Red     0      0    1
